export const ADDCATEGORY_OPEN_MODAL_SUCCESS ='ADDCATEGORY_OPEN_MODAL_SUCCESS'
export const ADDCATEGORY_CLOSE_MODAL_SUCCESS ='ADDCATEGORY_CLOSE_MODAL_SUCCESS'
export const ADD_CATEGORY_FIELD_CHANGE = 'ADD_CATEGORY_FIELD_CHANGE'
export const ADD_CATEGORY_SUCCESS ='ADD_CATEGORY_SUCCESS'

export const ADD_CATEGORY_EDIT ='ADD_CATEGORY_EDIT'
export const ADD_CATEGORY_GET_DATA ='ADD_CATEGORY_GET_DATA'
export const ADD_CATEGORY_SAVE_DATA ='ADD_CATEGORY_GET_DATA'
