export const ADD_NEW_PRODUCT_OPEN_MODAL_SUCCESS ='ADD_NEW_PRODUCT_OPEN_MODAL_SUCCESS'
export const ADD_NEW_PRODUCT_CLOSE_MODAL_SUCCESS ='ADD_NEW_PRODUCT_CLOSE_MODAL_SUCCESS'
export const ADD_NEW_PRODUCT_FIELD_CHANGE = 'ADD_NEW_PRODUCT_FIELD_CHANGE';
export const ADD_NEWPRODUCT_SAVE_DATA ='ADD_NEWPRODUCT_SAVE_DATA';
export const ADD_NEWPRODUCT_SUCCESS = 'ADD_NEWPRODUCT_SUCCESS';
export const ADD_NEW_PRODUCT_GET_DATA = 'ADD_NEW_PRODUCT_GET_DATA';
export const ADD_NEWPRODUCT_SUCCESS_EDIT ='ADD_NEWPRODUCT_SUCCESS_EDIT';

export const GET_SELECTED_PRODUCT_DATA = 'GET_SELECTED_PRODUCT_DATA';
export const OPEN_EDIT_PRODUCT_DATA_MODAL = 'OPEN_EDIT_PRODUCT_DATA_MODAL';
export const CLOSE_EDIT_PRODUCT_DATA_MODAL = 'CLOSE_EDIT_PRODUCT_DATA_MODAL';
export const EDIT_PRODUCT_DATA_FIELD_CHANGE = 'EDIT_PRODUCT_DATA_FIELD_CHANGE';
