export const ADD_NEW_SUPPLIER_FIELD_CHANGE = 'ADD_NEW_SUPPLIER_FIELD_CHANGE';
export const ADD_SUPPLIER_SAVE_DATA ='ADD_NEW_SUPPLIER_SAVE_DATA';
export const ADD_NEW_SUPPLIER_SUCCESS = 'ADD_NEW_SUPPLIER_SUCCESS';
export const ADD_SUPPLIER_GET_DATA = 'ADD_SUPPLIER_GET_DATA';
export const OPEN_ADD_NEW_SUPPLIER_MODAL = 'OPEN_ADD_NEW_SUPPLIER_MODAL';
export const CLOSE_ADD_NEW_SUPPLIER_MODAL = 'CLOSE_ADD_NEW_SUPPLIER_MODAL';
export const GET_SUPPLIERS_DATA_SUCCESS = 'GET_SUPPLIERS_DATA_SUCCESS';
