export const ADDUSER_OPEN_MODAL_SUCCESS = 'ADDUSER_OPEN_MODAL_SUCCESS'
export const ADDUSER_CLOSE_MODAL_SUCCESS = 'ADDUSER_CLOSE_MODAL_SUCCESS'
export const ADD_USER_FIELD_CHANGE = 'ADD_USER_FIEL_CHANGE'
export const ADD_USER_SUCCESS ='ADD_USER_SUCCESS'
