export const AUTH_ACCOUNT_RECEIVE = 'AUTH_ACCOUNT_RECEIVE';
export const AUTH_LOGIN_FAILED = 'AUTH_LOGIN_FAILED';
export const AUTH_LOGOUT_SUCCESS = 'AUTH_LOGOUT_SUCCESS';
export const AUTH_LOGIN_PENDING = 'AUTH_LOGIN_PENDING';
