export const DIALOG_OPEN_ALERT = 'DIALOG_OPEN_ALERT';
export const DIALOG_CLOSE_ALERT = 'DIALOG_CLOSE_ALERT';

export const DIALOG_OPEN_CONFIRM = 'DIALOG_OPEN_CONFIRM';
export const DIALOG_CLOSE_CONFIRM = 'DIALOG_CLOSE_CONFIRM';
export const DIALOG_OPEN_CONFIRM_OBJECT = 'DIALOG_OPEN_CONFIRM_OBJECT';
export const DIALOG_CLOSE_CONFIRM_OBJECT = 'DIALOG_CLOSE_CONFIRM_OBJECT';

export const DIALOG_OPEN_PROMPT = 'DIALOG_OPEN_PROMPT';
export const DIALOG_CLOSE_PROMPT = 'DIALOG_CLOSE_PROMPT';

export const DIALOG_ADDNOTIFICATION = 'DIALOG_ADDNOTIFICATION';
export const DIALOG_CLEARNOTIFICATIONSTORE = 'DIALOG_CLEARNOTIFICATIONSTORE';
