export const OPEN_STOCK_IN_MODAL_SUCCESS = 'OPEN_STOCK_IN_MODAL_SUCCESS';
export const CLOSE_STOCK_IN_MODAL_SUCCESS = 'CLOSE_STOCK_IN_MODAL_SUCCESS';
export const SET_DEFAULT_PRODUCT = 'SET_DEFAULT_PRODUCT';
export const ADD_MORE_ROWS_SUCCESS = 'ADD_MORE_ROWS_SUCCESS';
export const DELETE_ROWS_SUCCESS = 'DELETE_ROWS_SUCCESS';
export const SELECT_PRODUCT_FIELD_CHANGE = 'SELECT_PRODUCT_FIELD_CHANGE';