export const GET_PRODUCTS_DATA_SUCCESS = 'GET_PRODUCTS_DATA_SUCCESS'
export const SEARCH_PRODUCT_FOUND = 'SEARCH_PRODUCT_FOUND'
export const SEARCH_PRODUCT_FIELD_CHANGE = 'SEARCH_PRODUCT_FIELD_CHANGE'